Repository MIT-Emerging-Talent/ET6-foundations-group-06, pull requests merged in 2025-01, with the labels that each got.

#11 Contributing
  CONTRIBUTING.md
  README.md
Labels: documentation

#23 added the constraints
  collaboration/constraints.md
Labels: documentation, enhancement

#31 convert_bin_dec_hex
  solutions/convert_bin_dec_hex.py
  solutions/tests/test_convert_bin_dec_hex.py
Labels: Challenge

#21 subtracting numbers
  solutions/subtraction.py
  solutions/tests/test_subtraction.py
Labels: Challenge

#27 filtering a list
  solutions/filter_list.py
  solutions/tests/test_filter_list.py
Labels: Challenge

#49 repeat character
  solutions/repeat_character.py
  solutions/tests/test_repeat_character.py
Labels: Challenge

#34 Fuzz buzz
  solutions/fizz_buzz.py
  solutions/tests/test_fizz_buzz.py
Labels: Challenge

#53 Leap year Checker
  .vscode/settings.json
  solutions/leap_year_checker.py
  solutions/tests/test_leap_year_checker.py
Labels: Challenge

#42 Challenge_sum_even_odd
  .DS_Store
  solutions/sum_even_and_odd.py
  solutions/tests/test_sum_even_and_odd.py
Labels: Challenge

#60 checklist updates post-Q&A
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#61 Revert "Challenge_sum_even_odd"
  .DS_Store
  solutions/sum_even_and_odd.py
  solutions/tests/test_sum_even_and_odd.py
Labels: bug

#65 Delete .DS_Store
  .DS_Store
Labels: invalid

#69 Version whithout DS files
  solutions/sum_even_and_odd.py
  solutions/tests/test_sum_even_odd.py
Labels: Challenge

#74 Update .gitignore
  .gitignore
Labels: enhancement

#51 calculate_average
  solutions/calculate_average.py
  solutions/tests/test_calculate_average.py
Labels: Challenge

#73 Find second largest number
  solutions/find_second_largest.py
  solutions/tests/test_find_second_largest.py
Labels: Challenge

#80 Update communication
  collaboration/communication.md
Labels: documentation

#77 Sum_list
  solutions/sum_list.py
  solutions/tests/test_sum_list.py
Labels: Challenge

#83 Update retrospective.md
  collaboration/retrospective.md
Labels: documentation

#85 added notes and my free time
  collaboration/communication.md
  notes/README.md
Labels: documentation

#39 factorial
  solutions/factorial.py
  solutions/tests/test_factorial.py
Labels: Challenge

#87 Update retrospective.md
  collaboration/retrospective.md
Labels: documentation
